config/routes.rb
Rails.application.routes.draw do
 root 'products#home'
resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :find_product, only: [:show, :destroy] 


# index will change
def index 
@products = Product.where(category: params[:category])#.where( location: params[:location])

 @products.each do |product|
product_end_date = product.created_at += 5
if product_end_date <= Time.now
	product.destroy
end
 end

end

def home
	end

def new
@product = Product.new
end

def create
 @product = Product.new(product_params)
if @product.save
	redirect_to @product
	else
	render 'new'
	end 
end

def show
end

	def destroy
@product.destroy
redirect_to root_path

=begin
	if product created at time plus 14 days == current time
		send notice to user && destroy product
=end
end

private

def find_product
	@product = Product.find(params[:id])
end

def product_params
	params.require(:product).permit(:type, :category, :title, :body, :price, :location, :email, :phone)
end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/home.html.erb
<%= link_to "post to classifieds", new_product_path %>
<p>
<br>
<%= link_to "sporting goods", products_path(:category => :sporting)%>
<br>
<%= link_to "cars and trucks", products_path(:category => :cars)%>
</p>

app/views/products/index.html.erb
<% @products.each do |product| %>
<p>
<%= link_to product.title, product %>
</p>
<% end %>

<% if @products.to_a.empty? %>
<p> No Listings </p>
<% end %>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :category %>
<% f.radio_button :category, 'category', :checked => true %> 
<br>

<p>
<%= f.radio_button :category, 'sporting' %>
sporting
</p>

<p>
<%= f.radio_button :category, 'cars' %>
cars
</p>

<br>
<%= f.submit %>
<% end %>

app/views/products/show.html.erb
<%= @product.title %>